Organize & Fix up Scansat MM Cfg patch, Added Missing Modules
KSP-RO/USProbesPack pull request #8
Opened 2020-05-31 05:22 UTC by vader111

Reorganize Cfg patch making it looks tidier. Added missing Scansat Modules to the realsolarsytem section to add full function to the parts. Also Fixed Issue #5

2020-07-18 20:26 UTC, DRVeyl requested changes
Use of `:FOR[SCANsat]` as a pass designator here is a bad practice, since it satisfies `:NEEDS[SCANSat]` for MM passes even when SCANsat is not installed.  Please fix this by changing ALL `:FOR[SCANSat]` passes to `:AFTER[SCANsat]` or `:BEFORE[SCANsat]`

These changes look fine in general, appears there is a lot of whitespace cleanup done.

RN might take issue with some of the EC consumption rate changes.  I don't know how much the overall part EC consumption balance has been done already and if the changes here will impact that.

2020-07-18 20:32 UTC, vader111 commented
you caught me just as i was about to head to bed. I will take a look at it tomorrow.

But with the EC charge rates i just added the RSS scansat EC values, but i can change them back if need be.

2020-07-18 20:35 UTC, DRVeyl commented
Tomorrow is plenty fine.  I don't have commit rights here (otherwise I would have just fixed the pass issue myself), I guess this needs @raidernick 's response on what EC values he wants and to actually merge.

2020-07-19 13:27 UTC, DRVeyl approved these changes

2020-08-14 17:28 UTC, merged